config/routes.rb
PinkTeam::Application.routes.draw do
  root :to => "web_weight#index"
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/sample', to: 'sample_sessions#create', as: 'create_sample_session'
  get "/logout/", to: "sessions#destroy", as: 'logout'
  get "/teams/:id/recalculate", to: 'teams#recalculate', as: 'team_recalculate'

  resources :teams do
    resources :works
  end

  get ':action', controller: 'web_weight'
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  belongs_to :site
  has_one :screenshot
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :site
  mount_uploader :screenshot, ScreenshotUploader

  default_scope { order(:created_at) }

  def push_points(points, team_id)
    update_attributes(points: points)
    Pusher["team_#{team_id}"].trigger('push_points', {site_id: site.id, points: points})
  end

  def push_screenshot(screenshot_path, team_id)
    self.screenshot = File.open(screenshot_path)
    self.save
    Pusher["team_#{team_id}"].trigger('push_screenshot', {site_id: site.id, thumb_url: self.screenshot.thumb.url})
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :works
  has_many :teams, through: :works
  has_many :scores

  def need_score_refresh?
    last_score_at ? last_score_at < 8.week.ago : true
  end

  def last_score_at
    last_score.try(:created_at)
  end

  def screenshot
    last_score.screenshot
  end

  def points
    last_score.points
  end

  private

  def last_score
    scores.last
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :works
  has_many :sites, through: :works

  has_and_belongs_to_many :users

  default_scope { order('score DESC') }

  def self.random
    order("RAND()").first
  end

  def position_in_leaderboard
    Team.where('score <= ?', score).count
  end 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications

  has_and_belongs_to_many :teams
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :team
  belongs_to :site

  delegate :url, :screenshot, :points, to: :site, allow_nil: true
  default_scope { order('created_at DESC') } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/sample_sessions_controller.rb
class SampleSessionsController < ApplicationController
  def create
    user = User.create(sample: true, login: 'guest')

    session[:user_id] = user.id

    if user.teams.empty?
      redirect_to new_team_url, :notice => "Signed in as #{user.login}!"
    else
      redirect_to team_url(user.teams.first), :notice => "Signed in!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]

    authentication = 
      Authentication.where(provider: auth.provider, uid: auth.uid).first || 
      Authentication.create(provider: auth.provider, uid: auth.uid)

    user = authentication.user || User.create(login: auth.info.nickname).tap do |user|
      authentication.update(user: user)
    end

    session[:user_id] = user.id

    if user.teams.empty?
      redirect_to new_team_url, :notice => "Signed in as #{user.login}!"
    else
      redirect_to team_url(user.teams.first), :notice => "Signed in!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/teams_controller.rb
class TeamsController < WebWeightController
  def index
    @teams = Team.all
  end

  def new
    @team = current_user.teams.new
  end

  def create
    @team = Team.create(permitted_params[:team]).tap do |team|
      team.users << current_user
    end

    redirect_to team_url(@team)
  end

  def edit
    @team = current_user.teams.first
  end

  def update
    @team = Team.find(params[:id]).tap do |team|
      team.update(permitted_params[:team])
    end

    redirect_to team_url(@team)
  end

  def show
    @team = Team.find(params[:id])
  end

  def recalculate
    @team = Team.find(params[:id])
    TeamRankUpdater.run(@team)

    redirect_to edit_team_url(@team)
  end

  protected

    def permitted_params
      params.permit(team: [:url, :name, :description])
    end
end

app/controllers/web_weight_controller.rb
class WebWeightController < ApplicationController
  def index
    
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def create
    @team = Team.find(params[:team_id])
    CreateWork.run(@team, params)
    TeamRankUpdater.run(@team)

    redirect_to edit_team_url(@team)
  end

  def destroy
    @team = Team.find(params[:team_id])
    @team.works.find(params[:id]).destroy
    TeamRankUpdater.run(@team)

    redirect_to edit_team_url(@team)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text = nil)
    return '' if text.nil?

    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @markdown.render(text)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_active(controller, action, id = nil)
    if id 
      params[:controller] == controller && params[:action] == action && params[:id] == id ? "active" : nil
    else
      params[:controller] == controller && params[:action] == action ? "active" : nil    
    end  
  end

end

app/helpers/sample_sessions_helper.rb
module SampleSessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/web_weight_helper.rb
module WebWeightHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/application/_cloud.html.erb
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 200 100" preserveAspectRatio="none">
    <path d="M-5 100 Q 0 20 5 100 Z
             M0 100 Q 5 0 10 100
             M5 100 Q 10 30 15 100
             M10 100 Q 15 10 20 100
             M15 100 Q 20 30 25 100
             M20 100 Q 25 -10 30 100
             M25 100 Q 30 10 35 100
             M30 100 Q 35 30 40 100
             M35 100 Q 40 10 45 100
             M40 100 Q 45 50 50 100
             M45 100 Q 50 20 55 100
             M50 100 Q 55 40 60 100
             M55 100 Q 60 60 65 100
             M60 100 Q 65 50 70 100
             M65 100 Q 70 20 75 100
             M70 100 Q 75 45 80 100
             M75 100 Q 80 30 85 100
             M80 100 Q 85 20 90 100
             M85 100 Q 90 50 95 100
             M90 100 Q 95 25 100 100
             M95 100 Q 100 15 105 100
             M100 100 Q 105 0   110 100
             M105 100 Q 110 30  115 100
             M110 100 Q 115 10  120 100
             M115 100 Q 120 30  125 100
             M120 100 Q 125 -10 130 100
             M125 100 Q 130 10  135 100
             M130 100 Q 135 30  140 100
             M135 100 Q 140 10  145 100
             M140 100 Q 145 50  150 100
             M145 100 Q 150 20  155 100
             M150 100 Q 155 40  160 100
             M155 100 Q 160 60  165 100
             M160 100 Q 165 50  170 100
             M165 100 Q 170 20  175 100
             M170 100 Q 175 45  180 100
             M175 100 Q 180 30  185 100
             M180 100 Q 185 20  190 100
             M185 100 Q 190 50  195 100
             M190 100 Q 195 25  200 100 Z">
    </path>
  </svg>
  

app/views/application/_footer.html.haml
%h2
  %a{:href => "/about/"}
    Credits
%p
  Made in
  = link_to("weLaika", "http://dev.welaika.com")
  by 
  != "#{link_to("Filippo Gangi Dino","http://github.com/mukkoo")}, "
  != "#{link_to("Alessandro Fazzi","http://github.com/pioneerskies")}, "
  != "#{link_to("Fabrizio Monti","http://github.com/delphaber")}, "
  != "#{link_to("Silvano Stralla","http://github.com/sistrall")}."

app/views/application/_nav_main.html.haml
.nav-main
  %a{:href => root_url}
    .logo= image_tag "logo.png", :alt => "Size Matters", height: "120px"
  %nav
    %ul
      - if current_user
        - if current_user.teams.first && !current_user.teams.first.new_record?
          %li(class="#{is_active('teams', 'show', current_user.teams.first.id.to_s)}")
            %h4= link_to "You, the real #{current_user.login}", team_url(current_user.teams.first), class: 'hard-shadow'
          %li(class="#{is_active('teams', 'edit')}")
            %h4= link_to 'Manage', edit_team_url(current_user.teams.first), class: 'hard-shadow'
        - else
          %li(class="#{is_active('teams', 'new')}")
            %h4= link_to 'Add your team', new_team_url, class: 'hard-shadow'
      - else
        %li(class="#{is_active('web_weight', 'index')}")
          %h4= link_to 'Home', root_url, class: 'hard-shadow'
      %li(class="#{is_active('teams', 'index')}")
        %h4= link_to 'Leaderboard', teams_url, class: 'hard-shadow'
      %li(class="#{is_active('web_weight', 'about')}")
        %h4= link_to 'About', '/about/', class: 'hard-shadow'
      %li
        %h4
          - if current_user
            = link_to 'Logout', logout_url, class: 'hard-shadow'
          - else
            = link_to "Sign in with Github", "/auth/github", class: 'hard-shadow'

app/views/application/_nav_session.html.haml
.nav-session
  %nav
    %ul
      %li= link_to "Sign in with Github", "/auth/github", class: 'green button'
      %li= link_to "Login as a sample user", create_sample_session_url, class: 'green button'
      - if team = Team.random
        %li= link_to "Visit random team", team_url(team), class: 'green button'

app/views/application/_works.html.haml
%svg#clouds{height: "100", preserveaspectratio: "none", version: "1.1", viewbox: "0 0 100 100", width: "100%", xmlns: "http://www.w3.org/2000/svg"}
  %path{d: "M-5 100 Q 0 20 5 100 Z\r\n\t\t\t\t\t\t M0 100 Q 5 0 10 100\r\n\t\t\t\t\t\t M5 100 Q 10 30 15 100\r\n\t\t\t\t\t\t M10 100 Q 15 10 20 100\r\n\t\t\t\t\t\t M15 100 Q 20 30 25 100\r\n\t\t\t\t\t\t M20 100 Q 25 -10 30 100\r\n\t\t\t\t\t\t M25 100 Q 30 10 35 100\r\n\t\t\t\t\t\t M30 100 Q 35 30 40 100\r\n\t\t\t\t\t\t M35 100 Q 40 10 45 100\r\n\t\t\t\t\t\t M40 100 Q 45 50 50 100\r\n\t\t\t\t\t\t M45 100 Q 50 20 55 100\r\n\t\t\t\t\t\t M50 100 Q 55 40 60 100\r\n\t\t\t\t\t\t M55 100 Q 60 60 65 100\r\n\t\t\t\t\t\t M60 100 Q 65 50 70 100\r\n\t\t\t\t\t\t M65 100 Q 70 20 75 100\r\n\t\t\t\t\t\t M70 100 Q 75 45 80 100\r\n\t\t\t\t\t\t M75 100 Q 80 30 85 100\r\n\t\t\t\t\t\t M80 100 Q 85 20 90 100\r\n\t\t\t\t\t\t M85 100 Q 90 50 95 100\r\n\t\t\t\t\t\t M90 100 Q 95 25 100 100\r\n\t\t\t\t\t\t M95 100 Q 100 15 105 100 Z"}

app/views/application/_wrapper.html.haml
.wrapper
  = yield

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>SizeMatters</title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag 'modernizr' %>

  <!-- Initializes the modernizr and actually perform the checks. Enable this
       if you need the modernizr, but remember to only do the actual checks
       that you need. -->
  <%= javascript_tag "Modernizr.load();" %>
  <script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <!-- Add your site or application content here -->
  <header>
    <div class="wrapper">
      <%= render 'nav_main' %>
    </div>
  </header>

  <section>
    <%= yield %>
  </section>

  <footer>
    <div class="wrapper">
      <%= render 'footer' %>
    </div>
  </footer>

  <!-- JavaScript at the bottom for fast page loading: http://developer.yahoo.com/performance/rules.html#js_bottom -->
  <%= javascript_include_tag 'application' %>

  <% if Rails.env.production? %>
  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
  <% end %>
  <!-- Paste this before your front page's </body> tag. -->
  <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
</body>
</html>

app/views/web_weight/about.html.haml
= render layout: 'wrapper' do
  %article.about
    :markdown
      About SizeMatte.rs?
      =====================

      SizeMatte.rs is web ranking for the rest of us.

      If you're a freelancer or a small web agency, you can load all the websites you've worked on and get an estimate of your total web size.

      We sum ratings of your sites and give you a score based on a supersecret algorithm.

      This project has been developed in 48 hours with love and caffeine, during the 2013 Rails Rumble at [weLaika's](http://dev.welaika.com).

      Developers: [Filippo Gangi Dino](http://github.com/mukkoo), [Alessandro Fazzi](http://github.com/pioneerskies), [Fabrizio Monti](http://github.com/delphaber), [Silvano Stralla](http://github.com/sistrall)

app/views/web_weight/index.html.haml
= render layout: 'wrapper' do
  %aside= image_tag "tape.png"
  %article.home
    .text-block
      %h1.title Web ranking for the rest of us.
      %p Get a total web rank for all sites you've worked on. Freelancers, small web agencies, this is for you!
      %p Compare your size with the one of your friends or competitors. Because, you know... size matters.
      %p This project has been developed in 48 hours with love and caffeine, during the 2013 Rails Rumble.

    = render 'nav_session'

app/views/works/_work.html.haml
- work = present(work)
.media.work(data-site-id="#{work.site.id}")
  != work.thumb
  .content
    %div= work.name
    %div= work.host
    %div= link_to "Take a look", work.url, {target: "_blank", class: "hard-shadow"}
    %div.site-points= work.formatted_points
  - if show_delete
    = button_to "X", [@team, work], method: 'delete', confirm: "You're deleting your hard work! Are you sure?", class: 'delete hard-shadow-red'